# Generated by Django 6.0.6 on 2026-07-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_song_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketstub',
            name='energy_score',
        ),
        migrations.RemoveField(
            model_name='ticketstub',
            name='genre_tags',
        ),
        migrations.RemoveField(
            model_name='ticketstub',
            name='mood_tags',
        ),
        migrations.AddField(
            model_name='concert',
            name='energy_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='concert',
            name='mood_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ticketstub',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stubs', to='concerts.concert'),
        ),
    ]
