# Generated by Django 6.0.6 on 2026-07-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_remove_ticketstub_energy_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstub',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stubs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
