# Generated by Django 6.0.6 on 2026-08-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_ticketstub_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstub',
            name='design_seed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
