# Generated by Django 6.0.6 on 2026-07-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_tags', models.JSONField(default=list)),
                ('energy_score', models.IntegerField()),
                ('genre_tags', models.JSONField(default=list)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('design_seed', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stub', to='concerts.concert')),
            ],
        ),
    ]
