# Generated by Django 6.0.6 on 2026-07-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_ticketstub'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
